{{
    config(
        materialized='incremental',
        unique_key='CORRELATION_ID',
        schema='PROVIDERPDM_CORE_TARGET',
        alias='TRANSMISSION_AUDIT_LOG',
        tags=['marts', 'core']
    )
}}

SELECT
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_AUDIT_LOG_SK::VARCHAR(200) AS TRANSMISSION_AUDIT_LOG_SK,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_ID::VARCHAR(200) AS ENTITY_ID,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_ID_QUALIFIER_NAME::VARCHAR(72) AS ENTITY_ID_QUALIFIER_NAME,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_TYPE_CODE::VARCHAR(80) AS ENTITY_TYPE_CODE,
    TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') AS ENTITY_UPDATE_TMSTP,
    TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') AS TRANSMISSION_TMSTP,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_STATUS_NAME::VARCHAR(72) AS TRANSMISSION_STATUS_NAME,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_ERROR_TEXT::VARCHAR(4000) AS TRANSMISSION_ERROR_TEXT,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_ERROR_NAME::VARCHAR(72) AS TRANSMISSION_ERROR_NAME,
    TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID::VARCHAR(100) AS CORRELATION_ID,
    CASE 
        WHEN TRY_PARSE_JSON(RECORD_CONTENT):RESPONSE_OBJ::VARCHAR IS NOT NULL 
        AND TRY_PARSE_JSON(RECORD_CONTENT):RESPONSE_OBJ::VARCHAR != ''
        THEN PARSE_JSON(TRY_PARSE_JSON(RECORD_CONTENT):RESPONSE_OBJ::VARCHAR)
        ELSE NULL
    END AS RESPONSE_OBJ,
    CASE 
        WHEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):INSERT_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') IS NOT NULL 
        THEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):INSERT_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS')
        ELSE NULL
    END AS INSERT_TMSTP,
    CASE 
        WHEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') IS NOT NULL 
        THEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS')
        ELSE NULL
    END AS UPDATE_TMSTP,
    TRY_PARSE_JSON(RECORD_CONTENT):INSERT_USER_ID::VARCHAR(100) AS INSERT_USER_ID,
    TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_USER_ID::VARCHAR(100) AS UPDATE_USER_ID,
    TRY_PARSE_JSON(RECORD_CONTENT):DELETED_IND::VARCHAR(1) AS DELETED_IND,
    TRY_PARSE_JSON(RECORD_CONTENT):SOURCE_SYSTEM_CODE::VARCHAR(30) AS SOURCE_SYSTEM_CODE
FROM {{ source('providerpdm_core_raw', 'TRANSMISSION_AUDIT_LOG') }}
WHERE 
    TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID IS NOT NULL
    AND TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID != ''
    
    {% if is_incremental() %}
    -- Incremental logic using dbt's is_incremental() macro
    AND TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID::VARCHAR NOT IN (
        SELECT CORRELATION_ID 
        FROM {{ this }}
    )
    {% endif %}