{{
    config(
        materialized='incremental',
        unique_key='correlation_id',
        schema='PROVIDERPDM_CORE_TARGET',
        alias='TRANSMISSION_AUDIT_LOG',
        tags=['marts', 'core'],
        incremental_strategy='merge'  # or 'delete+insert' for Snowflake
    )
}}

SELECT
    TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID::VARCHAR AS correlation_id,
    TRY_PARSE_JSON(RECORD_CONTENT):DELETED_IND::VARCHAR AS deleted_ind,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_ID::VARCHAR AS entity_id,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_ID_QUALIFIER_NAME::VARCHAR AS entity_id_qualifier_name,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_TYPE_CODE::VARCHAR AS entity_type_code,
    TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') AS entity_update_tmstp,
    CASE 
        WHEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):INSERT_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') IS NOT NULL 
        THEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):INSERT_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS')
        ELSE NULL
    END AS insert_tmstp,
    TRY_PARSE_JSON(RECORD_CONTENT):INSERT_USER_ID::VARCHAR AS insert_user_id,
    TRY_PARSE_JSON(RECORD_CONTENT):RESPONSE_OBJ::TEXT AS response_obj,
    TRY_PARSE_JSON(RECORD_CONTENT):SOURCE_SYSTEM_CODE::VARCHAR AS source_system_code,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_AUDIT_LOG_SK::VARCHAR AS transmission_audit_log_sk,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_ERROR_NAME::VARCHAR AS transmission_error_name,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_ERROR_TEXT::TEXT AS transmission_error_text,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_STATUS_NAME::VARCHAR AS transmission_status_name,
    TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') AS transmission_tmstp,
    CASE 
        WHEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') IS NOT NULL 
        THEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS')
        ELSE NULL
    END AS update_tmstp,
    TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_USER_ID::VARCHAR AS update_user_id,
    CURRENT_TIMESTAMP() AS load_timestamp,
    CASE 
        WHEN TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_STATUS_NAME::VARCHAR = 'Failure' THEN 'FAILED'
        WHEN TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_STATUS_NAME::VARCHAR = 'Success' THEN 'SUCCESS'
        ELSE 'UNKNOWN'
    END AS transmission_status_category
FROM {{ source('providerpdm_core_raw', 'TRANSMISSION_AUDIT_LOG') }}
WHERE 
    -- Filter for records with CORRELATION_ID
    TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID IS NOT NULL
    AND TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID != ''

{% if is_incremental() %}
    -- Incremental logic
    AND TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID::VARCHAR NOT IN (
        SELECT correlation_id 
        FROM {{ this }}
    )
{% endif %}