-- Create or replace the target table first (run once)
CREATE OR REPLACE TABLE PROVIDERPDM_CORE_TARGET.TRANSMISSION_AUDIT_LOG (
    CORRELATION_ID VARCHAR(255),
    DELETED_IND VARCHAR(1),
    ENTITY_ID VARCHAR(255),
    ENTITY_ID_QUALIFIER_NAME VARCHAR(255),
    ENTITY_TYPE_CODE VARCHAR(50),
    ENTITY_UPDATE_TMSTP TIMESTAMP_NTZ,
    INSERT_TMSTP TIMESTAMP_NTZ,
    INSERT_USER_ID VARCHAR(255),
    RESPONSE_OBJ TEXT,
    SOURCE_SYSTEM_CODE VARCHAR(50),
    TRANSMISSION_AUDIT_LOG_SK VARCHAR(255),
    TRANSMISSION_ERROR_NAME VARCHAR(255),
    TRANSMISSION_ERROR_TEXT TEXT,
    TRANSMISSION_STATUS_NAME VARCHAR(50),
    TRANSMISSION_TMSTP TIMESTAMP_NTZ,
    UPDATE_TMSTP TIMESTAMP_NTZ,
    UPDATE_USER_ID VARCHAR(255),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Incremental load with CORRELATION_ID filter
INSERT INTO PROVIDERPDM_CORE_TARGET.TRANSMISSION_AUDIT_LOG
(
    CORRELATION_ID,
    DELETED_IND,
    ENTITY_ID,
    ENTITY_ID_QUALIFIER_NAME,
    ENTITY_TYPE_CODE,
    ENTITY_UPDATE_TMSTP,
    INSERT_TMSTP,
    INSERT_USER_ID,
    RESPONSE_OBJ,
    SOURCE_SYSTEM_CODE,
    TRANSMISSION_AUDIT_LOG_SK,
    TRANSMISSION_ERROR_NAME,
    TRANSMISSION_ERROR_TEXT,
    TRANSMISSION_STATUS_NAME,
    TRANSMISSION_TMSTP,
    UPDATE_TMSTP,
    UPDATE_USER_ID
)
SELECT
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_AUDIT_LOG_SK::VARCHAR(200) AS TRANSMISSION_AUDIT_LOG_SK,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_ID::VARCHAR(200) AS ENTITY_ID,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_ID_QUALIFIER_NAME::VARCHAR(72) AS ENTITY_ID_QUALIFIER_NAME,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_TYPE_CODE::VARCHAR(80) AS ENTITY_TYPE_CODE,
    TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') AS ENTITY_UPDATE_TMSTP,
    TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') AS TRANSMISSION_TMSTP,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_ID_QUALIFIER_NAME::VARCHAR(72) AS ENTITY_ID_QUALIFIER_NAME,
    TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_TYPE_CODE::VARCHAR(80) AS ENTITY_TYPE_CODE,
    TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):ENTITY_UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') AS ENTITY_UPDATE_TMSTP,
    TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') AS TRANSMISSION_TMSTP,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_STATUS_NAME::VARCHAR(72) AS TRANSMISSION_STATUS_NAME,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_ERROR_TEXT::VARCHAR(4000) AS TRANSMISSION_ERROR_TEXT,
    TRY_PARSE_JSON(RECORD_CONTENT):TRANSMISSION_ERROR_NAME::VARCHAR(72) AS TRANSMISSION_ERROR_NAME,
    TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID::VARCHAR(100) AS CORRELATION_ID,
    CASE 
        WHEN TRY_PARSE_JSON(RECORD_CONTENT):RESPONSE_OBJ::VARCHAR IS NOT NULL 
        AND TRY_PARSE_JSON(RECORD_CONTENT):RESPONSE_OBJ::VARCHAR != ''
        THEN PARSE_JSON(TRY_PARSE_JSON(RECORD_CONTENT):RESPONSE_OBJ::VARCHAR)
        ELSE NULL
    END AS RESPONSE_OBJ,
    
    -- TIMESTAMP_NTZ(9)
    CASE 
        WHEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):INSERT_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') IS NOT NULL 
        THEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):INSERT_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS')
        ELSE NULL
    END AS INSERT_TMSTP,
    
    -- TIMESTAMP_NTZ(9)
    CASE 
        WHEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS') IS NOT NULL 
        THEN TRY_TO_TIMESTAMP_NTZ(TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_TMSTP::VARCHAR, 'YYYY-MM-DD HH24:MI:SS')
        ELSE NULL
    END AS UPDATE_TMSTP,
    TRY_PARSE_JSON(RECORD_CONTENT):INSERT_USER_ID::VARCHAR(100) AS INSERT_USER_ID,
    TRY_PARSE_JSON(RECORD_CONTENT):UPDATE_USER_ID::VARCHAR(100) AS UPDATE_USER_ID,
    TRY_PARSE_JSON(RECORD_CONTENT):DELETED_IND::VARCHAR(1) AS DELETED_IND,
    TRY_PARSE_JSON(RECORD_CONTENT):SOURCE_SYSTEM_CODE::VARCHAR(30) AS SOURCE_SYSTEM_CODE
FROM PROVIDERPDM_CORE_RAW.TRANSMISSION_AUDIT_LOG
WHERE 
    -- Only include records that have CORRELATION_ID in the JSON
    TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID IS NOT NULL
    AND TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID != ''
    -- Incremental load: Only get records not already in target
    AND NOT EXISTS (
        SELECT 1 
        FROM PROVIDERPDM_CORE_TARGET.TRANSMISSION_AUDIT_LOG t
        WHERE t.CORRELATION_ID = TRY_PARSE_JSON(RECORD_CONTENT):CORRELATION_ID::VARCHAR
    );